import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Card } from "@/components/ui/card";
import { NavigationLinks } from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="w-screen h-screen bg-slate-950">
        <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
          <Card className="flex-col md:flex bg-slate-950">
            <div className="border-b">
              <div className="flex h-16 items-center px-4">
                <NavigationLinks />
              </div>
            </div>
            <div className="flex-1 p-8 pt-6">{children}</div>
          </Card>
        </div>
      </body>
    </html>
  );
}
